export const ENV_VARS__DB_NAME = "DB_NAME";
export const ENV_VARS__DDB_LOCAL_URL = "DDB_LOCAL_URL";
export const ENV_VARS__TEST_EVENT_BUS_TOPIC = "TEST_EVENT_BUS_TOPIC";
export const ENV_VARS__EVENT_BUS_TOPIC = "EVENT_BUS_TOPIC";
export const ENV_VARS__ASYNC_CUD = "ASYNC_CUD";
export const ENV_VARS__TEST_DB_NAME = "TEST_DB_NAME";
export const ENV_VARS__APPSYNC_ENDPOINT_URL = "APPSYNC_ENDPOINT_URL";
export const ENV_VARS__DB_ENDPOINT = "DDB_LOCAL_URL";
